#!/usr/bin/env python3
import sys
import argparse
sys.path.insert(0, '../Remote')
import client

def parse_argument():
    parser = argparse.ArgumentParser()
    parser.add_argument("hostname", help="hostname")
    parser.add_argument('port', type=int, help='port')
    parser.add_argument('name',help='name')
    parser.add_argument('strategy',help='strategy')

    args = parser.parse_args()
    return args

if __name__ == "__main__":
    args = parse_argument()
    HOST = args.hostname
    PORT = args.port
    NAME = args.name
    STRATEGY = args.strategy

    client.main(HOST, PORT, NAME, STRATEGY)