#!/usr/bin/env python3
import sys
sys.path.insert(0, '../Remote')
import server

if __name__ == "__main__":
	if len(sys.argv) > 3:
		print('Invalid Arguments');
		exit(1);

	HOST = '127.0.0.1'
	PORT = 8000

	if len(sys.argv) == 2:
		PORT = int(sys.argv[1])
	elif len(sys.argv) == 3:
		HOST = sys.argv[1]
		PORT = int(sys.argv[2])

	server.main(HOST, PORT)

