# -------------35 distinct tiles whihch are represented by its own four paths --------------------

"""
[(('north', 1), ('north', 2)), (('east', 1), ('east', 2)), (('south', 1), ('south', 2)), (('west', 1), ('west', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('east', 2)), (('south', 1), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('east', 2)), (('south', 1), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('north', 2)), (('east', 1), ('south', 1)), (('east', 2), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('south', 1)), (('east', 2), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('north', 2)), (('east', 1), ('south', 2)), (('east', 2), ('west', 1)), (('south', 1), ('west', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('south', 2)), (('east', 2), ('west', 2)), (('south', 1), ('west', 1))]
[(('north', 1), ('north', 2)), (('east', 1), ('west', 1)), (('east', 2), ('south', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('west', 1)), (('east', 2), ('south', 2)), (('south', 1), ('west', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('west', 1)), (('east', 2), ('west', 2)), (('south', 1), ('south', 2))]
[(('north', 1), ('north', 2)), (('east', 1), ('west', 2)), (('east', 2), ('south', 1)), (('south', 2), ('west', 1))]
[(('north', 1), ('north', 2)), (('east', 1), ('west', 2)), (('east', 2), ('south', 2)), (('south', 1), ('west', 1))]
[(('north', 1), ('north', 2)), (('east', 1), ('west', 2)), (('east', 2), ('west', 1)), (('south', 1), ('south', 2))]
[(('north', 1), ('east', 1)), (('north', 2), ('east', 2)), (('south', 1), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('east', 1)), (('north', 2), ('east', 2)), (('south', 1), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('east', 1)), (('north', 2), ('south', 1)), (('east', 2), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('east', 1)), (('north', 2), ('south', 1)), (('east', 2), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('east', 1)), (('north', 2), ('south', 2)), (('east', 2), ('west', 1)), (('south', 1), ('west', 2))]
[(('north', 1), ('east', 1)), (('north', 2), ('south', 2)), (('east', 2), ('west', 2)), (('south', 1), ('west', 1))]
[(('north', 1), ('east', 1)), (('north', 2), ('west', 1)), (('east', 2), ('south', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('east', 1)), (('north', 2), ('west', 1)), (('east', 2), ('south', 2)), (('south', 1), ('west', 2))]
[(('north', 1), ('east', 1)), (('north', 2), ('west', 2)), (('east', 2), ('south', 1)), (('south', 2), ('west', 1))]
[(('north', 1), ('east', 1)), (('north', 2), ('west', 2)), (('east', 2), ('south', 2)), (('south', 1), ('west', 1))]
[(('north', 1), ('east', 2)), (('north', 2), ('east', 1)), (('south', 1), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('east', 2)), (('north', 2), ('south', 1)), (('east', 1), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('east', 2)), (('north', 2), ('south', 1)), (('east', 1), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('east', 2)), (('north', 2), ('south', 2)), (('east', 1), ('west', 1)), (('south', 1), ('west', 2))]
[(('north', 1), ('east', 2)), (('north', 2), ('west', 1)), (('east', 1), ('south', 2)), (('south', 1), ('west', 2))]
[(('north', 1), ('south', 1)), (('north', 2), ('east', 1)), (('east', 2), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('south', 1)), (('north', 2), ('east', 1)), (('east', 2), ('west', 2)), (('south', 2), ('west', 1))]
[(('north', 1), ('south', 1)), (('north', 2), ('east', 2)), (('east', 1), ('west', 1)), (('south', 2), ('west', 2))]
[(('north', 1), ('south', 1)), (('north', 2), ('south', 2)), (('east', 1), ('west', 1)), (('east', 2), ('west', 2))]
[(('north', 1), ('south', 1)), (('north', 2), ('south', 2)), (('east', 1), ('west', 2)), (('east', 2), ('west', 1))]
[(('north', 1), ('south', 2)), (('north', 2), ('south', 1)), (('east', 1), ('west', 2)), (('east', 2), ('west', 1))]
[(('north', 1), ('west', 2)), (('north', 2), ('east', 1)), (('east', 2), ('south', 1)), (('south', 2), ('west', 1))]
"""